language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.2
    - extra-google-m2repository
    - extra-android-m2repository

script: GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m" ./gradlew build check --stacktrace
